# Generated by Django 4.2.6 on 2023-10-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="회사명",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(help_text="국가", max_length=30)),
                ("area", models.CharField(help_text="지역", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Recruitment",
            fields=[
                (
                    "recruitment_id",
                    models.BigAutoField(
                        help_text="채용공고 id", primary_key=True, serialize=False
                    ),
                ),
                ("position", models.CharField(help_text="채용포지션", max_length=50)),
                ("compensation", models.IntegerField(help_text="채용보상금")),
                ("context", models.TextField(help_text="채용내용")),
                ("tech_stack", models.CharField(help_text="사용기술", max_length=100)),
                (
                    "company_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.BigAutoField(
                        help_text="유저 id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="유저명", max_length=50)),
                (
                    "recruitment_id",
                    models.ForeignKey(
                        db_column="recruitment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.recruitment",
                    ),
                ),
            ],
        ),
    ]
